### ISSUE TITLE
Axe suddenly doesn't break blocks

### ISSUE THREAD

**Issue by SageXejis** [Clark919/Origination-Modpack#11]
My axe suddenly doesn't break blocks. It'll swing for an attack, but will not break a block (crafting table, trees, etc). The other players on the server don't have this issue. It seems to be just me.

**Comment by Clark919** [comment]
Hi there, this is not actually a bug, but a feature of the Better Combat mod. I can't remember the specific keybind name off the top of my head, but I think it is bound to one of the side mouse buttons (M4/M5) by default, and toggles the state of your weapon to either break blocks or only swing for attacks. You can find this under the Better Combat section under controls in your options.
