### ISSUE TITLE
[I/Q] My Question/Issue

### ISSUE THREAD

**Issue by Asf4lis** [Clark919/Origination-Modpack#6]
For the Spatial Mage origin, the "pocket dimension" feature doesn't seem to work, even when using the Load Hotbar Activator hotkey (default: X). Wasn't sure if this was a product of the mod or me not using the correct hotkey (I can't seem to find any other hotkey closer to the one described in the screenshot). 

**Modpack Version:**
 1.19.2 V2.7.8

![Minecraft Screenshot 2023 03 06 - 11 33 57 80](https://user-images.githubusercontent.com/104204056/222995944-5fbdd1af-d731-4943-a972-f1bb9433eb6a.jpg)

**Comment by Clark919** [comment]
Hi there, this is leftover text from the original creator of the Origin, although I believe this feature was removed in the version of the Origin I added to the modpack. I have yet to modify this Origin at all, so I will remove this text in a future update. Thanks for the report.

**Comment by Clark919** [comment]
Fixed in version 2.9.0.
