### ISSUE TITLE
[REQUEST] Add Origins: Vampire mod

### ISSUE THREAD

**Issue by Venekiel** [Clark919/Origination-Modpack#8]
## What feature would you like to see in the Origination modpack?
Hello, I've seen your Origination Modpack and was wondering if my Vampire origin would fit it.

It has some similarities with Bollard's one but aiming for better balance and in-game experience.

It for exemple greatly enhances the bat form with no more invulnerability frames through the use of the Identity mod (which you will probably want to configure to fit in your pack, here is the config i use [identity_config.zip](https://github.com/Clark919/Origination-Modpack/files/11201248/identity_config.zip)).

_Side-note: be aware that Bollard does not like anyone using his pack as a modified version and reposting it._

## Relevant links to mods, or directions to where to find the feature you want me to add.
You can find Origins: Vampire  on curseforge and modrinth for mod and datapack versions :
Curseforge: [mod](https://www.curseforge.com/minecraft/mc-mods/origins-vampire)
Modrinth: [mod](https://modrinth.com/datapack/origins-vampire/version/v2.1.0+mod) / [datapack](https://modrinth.com/datapack/origins-vampire/version/v2.1.0)

For help about the datapack or to make suggestions / bug reports, you can join my Discord server: https://discord.com/invite/C6uYzAqXpA

**Comment by Clark919** [comment]
Hi, I like the look of this mod at a glance, and will consider adding it. Do bear in mind the way in which I initialise Origins within this pack will require some modification, and as I am lacking free time currently it may take some time for me to decide and take the necessary steps to implement this Origin into the client. If I do add the identity mod, I will likely go back and modify some Origins to allow them to shapeshift into these mobs, so this would come as part of an overhaul if I did add your mod. I imagine I will have some time for it within the next month, so I'll certainly look into it :)

**Comment by Clark919** [comment]
To follow up with this, I've tested your mod a bit and it's certainly an improvement to the one currently used within the modpack. With your permission, I am happy to include it and add some slight modifications (mainly adding powers to manage the weapon weight classes used within the modpack). You will be fully credited in the patchnotes and wiki of the modpack once added.

**Comment by Venekiel** [comment]
You have my permission to use and modify my mod to add it to your modpack, all I ask is that you add the link to the mod (or datapack) page in the description or in Curseforge's dependency tab as credit

**Comment by Clark919** [comment]
Added in v2.10.0
