### ISSUE TITLE
[BUG] My Issue

### ISSUE THREAD

**Issue by DigitalVaporeon** [Clark919/Origination-Modpack#9]
**Describe the bug**
The G key cannot be bound to open the inventory

**To Reproduce**
Steps to reproduce the behavior (add and remove steps as needed, describe clearly):
1.  Open controls menu
2.  Bind inventory key to G
3.  Try to open inventory with G

**Expected behavior**
The inventory should open when you press G instead of E. Instead it does nothing.

**Modpack Version:**
 1.19.2 1.0.0 Beta

**Comment by Clark919** [comment]
Hi, I'm not actually sure what causes this inconsistency. It's one of the default binds for Origins, but I remember testing some months ago and couldn't get G to work with any function. I presume one of the mods specifically reserves G for something, but I am unable to find which one. For now, I will not be fixing this issue.
